package com.beeant.dto;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table app_user
 *
 * @mbggenerated do_not_delete_during_merge Fri Mar 04 16:25:45 CST 2016
 */
public class AppUser implements Serializable {
    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   昵称
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private String userNickname;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private String userFullname;

    /**
     * Database Column Remarks:
     *   访问密码
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private String password;

    /**
     * Database Column Remarks:
     *   手机
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private String mobile;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private String email;

    /**
     * Database Column Remarks:
     *   性别
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private String gender;

    /**
     * Database Column Remarks:
     *   状态:停用inactive/启用active
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private String status;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   标记删除
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private String deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_user
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.user_id
     *
     * @return the value of app_user.user_id
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.user_id
     *
     * @param userId the value for app_user.user_id
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.user_name
     *
     * @return the value of app_user.user_name
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.user_name
     *
     * @param userName the value for app_user.user_name
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.user_nickname
     *
     * @return the value of app_user.user_nickname
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public String getUserNickname() {
        return userNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.user_nickname
     *
     * @param userNickname the value for app_user.user_nickname
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setUserNickname(String userNickname) {
        this.userNickname = userNickname == null ? null : userNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.user_fullname
     *
     * @return the value of app_user.user_fullname
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public String getUserFullname() {
        return userFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.user_fullname
     *
     * @param userFullname the value for app_user.user_fullname
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setUserFullname(String userFullname) {
        this.userFullname = userFullname == null ? null : userFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.password
     *
     * @return the value of app_user.password
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.password
     *
     * @param password the value for app_user.password
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.mobile
     *
     * @return the value of app_user.mobile
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.mobile
     *
     * @param mobile the value for app_user.mobile
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.email
     *
     * @return the value of app_user.email
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.email
     *
     * @param email the value for app_user.email
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.gender
     *
     * @return the value of app_user.gender
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.gender
     *
     * @param gender the value for app_user.gender
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.status
     *
     * @return the value of app_user.status
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.status
     *
     * @param status the value for app_user.status
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.birthday
     *
     * @return the value of app_user.birthday
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.birthday
     *
     * @param birthday the value for app_user.birthday
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.create_time
     *
     * @return the value of app_user.create_time
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.create_time
     *
     * @param createTime the value for app_user.create_time
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.deleted
     *
     * @return the value of app_user.deleted
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public String getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.deleted
     *
     * @param deleted the value for app_user.deleted
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setDeleted(String deleted) {
        this.deleted = deleted == null ? null : deleted.trim();
    }

    public boolean isNotNull() {
        return  null != this.userId || null != this.userName || null != this.userNickname || null != this.userFullname || null != this.password || null != this.mobile || null != this.email || null != this.gender || null != this.status || null != this.birthday || null != this.createTime || null != this.deleted;
    }
}