package com.beeant.dto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table app_user_role
 *
 * @mbggenerated do_not_delete_during_merge Fri Mar 04 16:25:45 CST 2016
 */
public class AppUserRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private String userRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_user_role
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_role.user_role_id
     *
     * @return the value of app_user_role.user_role_id
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public String getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_role.user_role_id
     *
     * @param userRoleId the value for app_user_role.user_role_id
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setUserRoleId(String userRoleId) {
        this.userRoleId = userRoleId == null ? null : userRoleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_role.user_id
     *
     * @return the value of app_user_role.user_id
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_role.user_id
     *
     * @param userId the value for app_user_role.user_id
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user_role.role_id
     *
     * @return the value of app_user_role.role_id
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user_role.role_id
     *
     * @param roleId the value for app_user_role.role_id
     *
     * @mbggenerated Fri Mar 04 16:25:45 CST 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    public boolean isNotNull() {
        return  null != this.userRoleId || null != this.userId || null != this.roleId;
    }
}